### ISSUE TITLE
Images are stretched at low breakpoints

### ISSUE THREAD

**Issue by le-dav** [bae-sh/tiptap-extension-resize-image#11]
Hi there,

Thanks for your work and your useful extension!

Just have an issue with resized image on responsive websites.
Let's say I resize an image, how can I ensure the image is not stretched when the screen width is lower than the resizing dimensions?

Wouldn't it be better to have some kind of failover putting the height to "auto" and the width at 100% once the screen size is too narrow? Or maintain the ratio depending on the screen size?
For me the 1st option would be kind of useful, and would stay in line with the default Image extension behaviour.

**Example of the issue:**
Image **not resized** on large screen : <img width="2269" alt="image" src="https://github.com/bae-sh/tiptap-extension-resize-image/assets/69483363/65d4d4e8-c782-44cc-aa5d-4f3f987b4a26">

Image **not resized** on a narrow screen : <img width="379" alt="image" src="https://github.com/bae-sh/tiptap-extension-resize-image/assets/69483363/a0bfc3a3-0b05-4f76-8515-cfb73203284b">

Image **resized** on large screen : <img width="2276" alt="image" src="https://github.com/bae-sh/tiptap-extension-resize-image/assets/69483363/680a1457-80fc-4924-a658-0d46b5b0a654">

Image **resized** on a narrow screen: it's stretched as it adapts the width, not the height <img width="379" alt="image" src="https://github.com/bae-sh/tiptap-extension-resize-image/assets/69483363/3af876b9-176b-43ce-be1b-e41e74912893">

Or have I missed something when implementing the extension?

**Comment by bae-sh** [comment]
Thank you for reporting the bug!

I missed a case when the browser width changes. I have fixed this issue and released [v1.1.8](https://github.com/bae-sh/tiptap-extension-resize-image/releases/tag/v1.1.8).

If you encounter any bugs or have any feedback, please feel free to report them.

Thanks :) @le-dav
