### ISSUE TITLE
Image Resizes to Full Width on Insertion

### ISSUE THREAD

**Issue by goldwizard13** [bae-sh/tiptap-extension-resize-image#13]
Hi there,

I'm using the tiptap-extension-resize-image (version 1.1.8) in my Tiptap editor, and I've encountered an issue where images are automatically stretched to the full width of the screen upon insertion. I would like to have the ability to insert images at their original dimensions and add custom styles to them.

Here are the details:

    Extension Version: tiptap-extension-resize-image v1.1.8
    Current Behavior: When an image is inserted, it automatically resizes to the full width of the editor. The style applied is width: 100%; height: auto;.
    Desired Behavior: I want the inserted images to retain their original dimensions. Additionally, I need to be able to specify custom styles for the images upon insertion.

I've tried configuring the extension with options such as defaultStyle and handleStyles, but they do not seem to affect the behavior of the inserted images. Here is what I attempted:

javascript

ImageResize.configure({
  handleStyles: {
    left: 'left: -4px; top: 50%; transform: translate(-50%, -50%); cursor: ew-resize;',
    right: 'right: -4px; top: 50%; transform: translate(50%, -50%); cursor: ew-resize;',
    top: 'top: -4px; left: 50%; transform: translate(-50%, -50%); cursor: ns-resize;',
    bottom: 'bottom: -4px; left: 50%; transform: translate(-50%, 50%); cursor: ns-resize;',
  },
  resizable: {
    enabled: true,
  },
  defaultStyle: {
    width: 'auto',
    height: 'auto',
  },
});

Unfortunately, this configuration does not seem to solve the issue.

Could you please provide guidance on how to achieve the desired behavior, or if there are any updates or additional options available that could help with this problem?

Thank you for your assistance!

**Comment by Luis17Paiva** [comment]
I have the same problem
