### ISSUE TITLE
Word wrap around image and custom html attributes

### ISSUE THREAD

**Issue by nandi95** [bae-sh/tiptap-extension-resize-image#3]
Very nice extension.

Have you considered adding a feature where the text wraps around the image?
Furthermore, I have had the configuration:
```js
HTMLAttributes: {
    loading: 'lazy'
}
```
for the base image extension but this is not applied to the image? Any chance adding support for that

**Comment by bae-sh** [comment]
Hi Nandi, Thanks for using my extension.

I found your suggestion very interesting, and I totally agree that HTMLAttributes should be included there.
I've noticed some HTMLAttributes aren't working right with the loading attribute.

```js
const editor = useEditor({
    extensions: [StarterKit, ImageResize],
    content: `<img src="https://source.unsplash.com/8xznAGy4HcY/800x400" loading="lazy"/> `,
  });
```

I'll get on fixing this ASAP. Thanks again!

**Comment by bae-sh** [comment]
I've resolved this issue and published [v1.1.5](https://github.com/bae-sh/tiptap-extension-resize-image/releases/tag/v1.1.5).
You can now use img attributes such as loading or any attributes

### example

```js
const editor = useEditor({
    extensions: [StarterKit, ImageResize],
    content: `<img src="https://source.unsplash.com/8xznAGy4HcY/800x400" loading="lazy" title="hello" width="800"/> `,
  });
```

However, I'm a bit confused because the Tiptap image extension doesn't seem to support this feature.
If you encounter any problems, feel free to leave a issue. Thanks.

**Comment by jan-schweiger** [comment]
Being able to write text next to an image like in Word would indeed be a great feature. At least it would nice if there was a blinking cursor on the right side of the image indicating one can safely press enter similar to Word / Google Docs.

**Comment by bae-sh** [comment]
Hi @jan-schweiger 

Thank you for your suggestion! I understand the feature you mentioned. I will consider how to add that blinking cursor with tiptap. If I develop the feature, I will include it in the next version.

If you have any solutions in mind, please feel free to modify and submit a PR. Thanks for your comment!

**Comment by jan-schweiger** [comment]
Great @bae-sh!

I implemented a Text wrap, by conditionally setting the text-wrap class. Then the following css (I use griffel.js) does the trick:
```
'& .node-image': {
  maxWidth: '100%',
},
'& .node-image:has(> div .image-wrap)': {
  float: 'left',
  marginRight: "10px"
},
'& .node-image:has(> div .image-wrap) + * + *': {
  clear: 'both',
},
'& .ProseMirror:after': {  // otherwise image is cut off on y-axis if no content follows
  content: "''",
  display: 'table',
  clear: 'both'
}
```

I hope this helps.
However, I have implemented a custom React version of your plugin.

**Comment by bae-sh** [comment]
That's a good solution! I would implement it based on your code. 
Thank you!!!
