### ISSUE TITLE
Images not persisting horizontal alignment when Editor has prop "editable" set to false

### ISSUE THREAD

**Issue by LumDermaku** [bae-sh/tiptap-extension-resize-image#4]
I am on a `Remix.run V2` app with `Vite`, `Node.Js 20.11.0`, `TipTap 2.4.0` and your extension library `1.1.5`. I also have another unofficial tiptap extension - `@aarkue/tiptap-math-extension` but I don't think it's interfering with the issue I'm having.

Since we save the content of the editor in our database, we then have to display it elsewhere. When we display it, we must set the tiptap config prop `editable` to `false`. After doing so, the whole content renders fine besides the image position. We are using the justify-content feature of your extension but it is not persisting the position when tiptap is not editable. Here's an example you can use for reproducing the issue:

```html
<p>some content, image on the next line:</p><img src="https://images.unsplash.com/photo-1513542789411-b6a5d4f31634?q=80&amp;w=1674&amp;auto=format&amp;fit=crop&amp;ixlib=rb-4.0.3&amp;ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D" style="width: 308px; height: 231.213px; cursor: pointer; justify-content: center;" draggable="true"><p></p><p>... the rest of the content under the image</p>
```

I am using the HTML output version of TipTap instead of JSON because of some compatibility issues with that other tiptap extension.

**Comment by LumDermaku** [comment]
@bae-sh now it looks like image size is also broken in v1.1.5. Regardless of the `editable` prop value and how you resize the image, it always displays the image as wide as it can.
Try it with this [photo](https://images.unsplash.com/photo-1560707303-4e980ce876ad?q=80&w=3732&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D/800x400) instead

**Comment by bae-sh** [comment]
Hi, @LumDermaku

Thank you for the bug report.

I checked the alignment doesn't work when editable is set to false, and the size is broken in v1.1.5.

I fixed the critical size bug in v1.1.6.

However, when editable is set to false, the img tag's parent node, a div tag with display: flex, is removed. I think the logic differs in Tiptap depending on the editable option.

I am considering how to solve this, but it is not easy for me. Pull requests are welcome!!!I hope you can solve this problem.

**Comment by Im-younique** [comment]
Hello, @LumDermaku 

I am a co-owner of this repository

We have identified a bug related to image alignment and are currently resolving it and proceeding with the PR process for #6 .

The version will be updated when the PR disappears after testing, so please check after that.

Thanks for your interest in our repository.

**Comment by LumDermaku** [comment]
Just tested it thoroughly, it's working great now.
Thanks a lot @Im-younique and @bae-sh, great job on this library.
